on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Which stage?'
        required: true
        type: choice
        options:
          - dev

jobs:
  remove:
    uses: ./.github/workflows/.sst-template.yml
    secrets: inherit
    with:
      stage: ${{ inputs.stage }}
      command: remove
